= Premium Capabilities

== Introduction

In addition to the core open-source Kill Bill platform, we also offer additional software packages to make it easier to deploy, operate and administer the system; we also provide additional features that go beyond the set of core subscription billing functionalities offered by the Kill Bill platform. Such premium capabilties are optional, and it is entirely possible to use the open-source Kill Bill platform at scale to address the most complex billing problems. The premium capabilities will however provide an easier experience and add further capabilties that go beyond core subscription billing.

Documentation around premium features will be flagged with a purple dot in the table of content as seen on this page to make it obvious for the reader. 

== AWS Images

We provide a series of AMIs that are tightly integrated with AWS and that make it easy to deploy Kill Bill in a cloud native environment. All our documentation supporting the use of these AMIs will have a banner specifying this is an AWS Marketplace only feature.

== Aviate

We provide a custom plugin to make it easier to administer the system and to also provide additional capabilities not included in the open-source solution. All our documentation supporting our Aviate plugin will have a banner specifying is an Aviate-only feature.




