=== Step 1 - Obtain the migrations to run

The `kpm migrate` command can be used to obtain database migrations.

*Command*

[source,bash]
----
kpm migrations github_repository from_tag to_tag
----

*Example*

To download the migration files to migrate the analytics plugin from  `8.0.0` to `8.1.0`:

[source,bash]
----
kpm migration killbill-analytics-plugin analytics-plugin-8.0.0 analytics-plugin-8.1.0
----

This command creates a temporary folder with the migration SQL statements and displays its path.

[NOTE]
*Note:* Because the implementation relies on the GitHub API, unauthenticated requests are subject to rate limiting. To work around it, generate a token via https://github.com/settings/tokens (default public, read-only, permissions will work) and specify it to KPM via `kpm migrations killbill killbill-0.22.32 killbill-0.24.0 --token=TOKEN`

=== Step 2 - Execute the migrations

The migrations can be executed either manually or using the https://documentation.red-gate.com/fd/quickstart-command-line-184127576.html[Flyway command-line tool].

==== Executing migrations manually

Execute the SQL scripts obtained above directly on your database.

==== Executing migrations via the Flyway Command-Line Tool

Migrations can also be executed using the Flyway command-line tool.

1. *Install Flyway Command-Line Tool:*
+
Follow the installation guide here: https://documentation.red-gate.com/fd/quickstart-command-line-184127576.html[Flyway CLI Installation].

2. *Run the Baseline Command (First-Time Use Only):*
+
If Flyway is being used the first time, run the `baseline` command to create the `flyway_schema_history` table.
+
*Command*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/killbill -user=<db_user> -password=<db_password> -table=<plugin_name>_schema_history baseline
----
+
*Example*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/killbill -user=root -password=killbill -table=analytics_schema_history baseline
----


3. *Run the `migrate` command to execute the migrations.*
+
*Command*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/<db_name> -user=<db_user> -password=<db_password> -locations=filesystem:<migrations_path> -table=<plugin_name>_schema_history migrate
----
+
*Example*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/killbill -user=root -password=killbill -locations=filesystem:C:/var/migrations -table=analytics_schema_history migrate
----


==== Additional Notes for Production Environments

In production environments, database access is often restricted and developers don’t necessarily have rights to execute DDL commands (i.e. CREATE, ALTER, DROP, etc. statements). In such cases, migrations can be executed as follows:

1. *Create the  `<plugin_name>_schema_history` table manually:*
+
[source, sql]
----
CREATE TABLE `<plugin_name>_schema_history` (
  `installed_rank` int(11) NOT NULL,
  `version` varchar(50) DEFAULT NULL,
  `description` varchar(200) NOT NULL,
  `type` varchar(20) NOT NULL,
  `script` varchar(1000) NOT NULL,
  `checksum` int(11) DEFAULT NULL,
  `installed_by` varchar(100) NOT NULL,
  `installed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` int(11) NOT NULL,
  `success` tinyint(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  KEY `schema_history_s_idx` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into <plugin_name>_schema_history (installed_rank, version, description, type, script, installed_by, installed_on, execution_time, success) VALUES (1, 1, '<< Flyway Baseline >>', 'BASELINE', '<< Flyway Baseline >>', 'admin', NOW(), 0, 1);
----
+
Ensure that you replace `<plugin_name>` with the name of a plugin like `analytics`.

2. *Run a Dry Run (if needed for review before applying migrations):*
+
Flyway CLI does not support dryRun directly, but you can use `-outputType=json` to review pending migrations:
+
*Command*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/<db_name> -user=<db_user> -password=<db_password> -table=<plugin_name>_schema_history info -outputType=json
----
+
*Example*
+
[source, bash]
----
flyway -url=jdbc:mysql://127.0.0.1:3306/killbill -user=root -password=password -locations=filesystem:C:/var/migrations-table=analytics_schema_history info -outputType=json
----
+
This will list pending migrations without applying them.